export const siteConfig = {
  name: "Angiely Hinojosa",
  role: "Estudiante de Educación Física",
  institution: "Universidad Nacional de San Antonio Abad del Cusco (UNSAAC)",
  location: "Cusco, Perú",
  title: "Angiely Hinojosa | Educación Física UNSAAC",
  description:
    "Portafolio de Angiely Hinojosa, estudiante de Educación Física en la UNSAAC enfocada en bienestar, deporte y formación integral.",
  url: "https://angiely-hinojosa.vercel.app",
  ogImage: "/images/og-angiely.svg",
  keywords: [
    "Educación Física",
    "UNSAAC",
    "Entrenamiento deportivo",
    "Bienestar integral",
    "Angiely Hinojosa",
    "Cusco",
    "Perú",
    "Educación deportiva",
    "Formación física",
    "Actividad física",
  ],
  links: {
    email: "mailto:angiely.hinojosa@unsaac.edu.pe",
    facebook: "https://www.facebook.com/angiely.hinojosa",
    linkedin: "https://www.linkedin.com/in/angiely-hinojosa",
    instagram: "https://www.instagram.com/angiely.fisica",
    whatsapp: "https://wa.me/51999999999",
  },
};
